apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero-webhook
  labels:
    app: velero-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velero-webhook
  template:
    metadata:
      labels:
        app: velero-webhook
    spec:
      serviceAccountName: velero-webhook
      containers:
        - name: velero-webhook
          image: thetrong/velero-webhook:v0
          imagePullPolicy: Always
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/certs
              readOnly: true
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: tls-certs
          secret:
            secretName: velero-webhook-tls